### ISSUE TITLE
Evidence

### ISSUE THREAD

**Issue by DanielBaird** [antijingoist/open-dyslexic#46]
As far as I could see on the opendyslexic.org site and on the Wikipedia article https://en.wikipedia.org/wiki/OpenDyslexic , there aren't any links to experimental evidence confirming the advantage of this font compared to a traditional font like Vera Sans.

This might be a decent PhD for someone.  This project should reach out to academic institutions and propose it as a project.
##

**Comment by pabeaufait** [comment]
Abbie (@antijingoist), 

I get the time limits, job, family, and all. Nevertheless, I did go web walk-about today, and compiled a few tentative findings here: 

- https://pabspotpourri.blogspot.jp/2017/09/a-few-dyslexia-resources.html

Hopefully someone will jump on close examination of OpenDyslexic in conjunction with other alternative fonts in the near future.

Paul

**Comment by pabeaufait** [comment]
Hello again, Abbie (@antijingoist).

I've found email addresses I believe belong to the author and supervisors of Renske de Leeuw's 2010 thesis examining the font, **Dyslexie**, that you'd listed on your [**Research**](https://opendyslexic.org/about-2/related-research/) page. 

> Special Font For Dyslexia?
> Master’s thesis[:] Renske de Leeuw
> First supervisor: Dr. T. van Leeuwen 
> Second supervisor: Prof. Dr. W.R. Joolingen 
> December 2010, University of Twente ([PDF](http://essay.utwente.nl/60474/1/MA_thesis_R_Leeuw.pdf), title page)

If the author of that thesis (de Leeuw, 2010) isn't keen on replicating her study for **OpenDyslexia**, I'd like to suggest that you contact the supervisors, confirm their roles with regard to de Leeuw's thesis, and ask whether they currently mentor anyone who'd be keen to have a go examining **OpenDyslexia**. 

Though I didn't find the supervisors at the University of Twente, Google did hit on their names at University of Utrecht (2017.09.12, below). The author seems to be at the University of Groningen:

- **R.R. (Renske) de Leeuw, MSc**
- r.r.de.leeuw@rug.nl
- http://www.rug.nl/staff/r.r.de.leeuw/

Top Google hits for supervisor's names (2017.09.12):

1st supervisor:
- **dr. T. (Tristan) van Leeuwen**
- T.vanLeeuwen@uu.nl
- [https://www.uu.nl/staff/TvanLeeuwen](https://www.uu.nl/staff/TvanLeeuwen)

2nd supervisor:
- **prof. dr. W.R. (Wouter) van Joolingen**
- W.R.vanJoolingen@uu.nl
- [https://www.uu.nl/staff/WRvanJoolingen/0](https://www.uu.nl/staff/WRvanJoolingen/0)

Abbie, please do follow-up here, and let us know whether you've contacted them, and whether they've replied.

Cheers, Paul

**Comment by antijingoist** [comment]
I'm compiling a list of existing research for the site migration, and I'll have it posted shortly (within a week or so). These were studies that either the authors themselves sent me without prompting, or people who saw the study that sent them to me.

I do not have time to spend contacting authors/researchers campaigning for studies. I'm just now getting to emails from several months ago.

If you want to, by all means go ahead.

**Comment by antijingoist** [comment]
Can't promise follow ups, but I am adding studies regardless of result to the website. I'll do it today.
