### ISSUE TITLE
Added to homebrew fonts cask

### ISSUE THREAD

**Issue by balupton** [antijingoist/open-dyslexic#54]
https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-opendyslexic.rb

You can now do `homebrew cask install font-opendyslexic` - would be cool to see this added to the "Linux" section on http://opendyslexic.org/download/ under a "Homebrew" section.

**Comment by kirbyfan64** [comment]
You mean the Mac section? A quick glance looks like that's a Mac program, not a Linux one.

**Comment by balupton** [comment]
Yeah, you're probably right. Figured it was a good fit for the package managers section though. Up to you.

**Comment by antijingoist** [comment]
Appened to page.
Thanks!
