### ISSUE TITLE
Add OpenDyslexic to cdnjs

### ISSUE THREAD

**Issue by TheTannerRyan** [antijingoist/open-dyslexic#57]
Add OpenDyslexic to cdnjs so people can use the fonts over a CDN for their websites: https://github.com/cdnjs/cdnjs

**Comment by kirbyfan64** [comment]
Not quite the same but close: https://github.com/jsdelivr/jsdelivr/pull/3959

**Comment by TheTannerRyan** [comment]
I don't see it on their website.
