### ISSUE TITLE
bad Cyrillic glyphs, OpenDyslexic Alta Bold-Italic scaling issues

### ISSUE THREAD

**Issue by ihaohu** [antijingoist/open-dyslexic#59]
want to report two issues we observed in the OpenDyslexic font version 2.
![aqf61zs5hmpuxwaaavemhrmxfaielm2mau6uoydf4vyda5ondj58tgvhmcf64p1rudbt_hercsir0aq3vw7rdey_sgnqovr_dpbuv7xmwcjhjcbrgolltv_rpzjmqo2umv-22vv0ebn9yx0eghpm9zj8ztxodgsogl3efckglmyegaxgjlojg9vqppv546ig72odzjqfmbn8u5a6bisvbrgyonkgtbi853uqdeilytzioyh-](https://cloud.githubusercontent.com/assets/11055897/11170430/d4951d1e-8b88-11e5-82f3-44347c347e64.png)

1. OpenDyslexicAlta-Regular.otf has 2x larger font face compare to any other
2. The OpenDyslexic-Regular.otf has issue on the Cyrillic glyphs

Please see the screen shot for details.

**Comment by antijingoist** [comment]
Fixed OpenDyslexicAlta Bold-Italic: rescaled glyphs to match the others. OTF and .glyphs files updated.

**Comment by antijingoist** [comment]
Fixed OpenDyslexic Regular: removed unfinished Cyrillic Glyphs. OTF and .glyphs files updated.

Closing this issue. Thank you for reporting this, and including a screenshot.
