### ISSUE TITLE
Monospace version

### ISSUE THREAD

**Issue by stevehjohn** [antijingoist/open-dyslexic#67]
Hi,
It might be a nice idea to have a monospace version of the font for dyslexic software developers?
Thanks,
Steve.

**Comment by frob** [comment]
From looking at #62, there is a monospace version though it has some issues.

**Comment by Aricg** [comment]
I downloaded the fedora package and there was no monospace variant. The default is unusable in the terminal.

**Comment by antijingoist** [comment]
Sorry, this was fixed in 62. I'll ensure it gets added in.
