### ISSUE TITLE
Using Open Dyslexic on https://www.opendyslexic.org/ itself

### ISSUE THREAD

**Issue by iHiD** [antijingoist/open-dyslexic#76]
Hello. I'm exploring using Open Dyslexic for the new version of [Exercism](https://exercism.io). 

As I was researching, I was a little confused to see that the Open Dyslexic site is rendering as Comic Sans, rather than using Open Dyslexic itself. I wondered if there was a reason for that or if something was broken there.

Thanks! 🙂

**Comment by antijingoist** [comment]
Long story short, I'm fixing it now. :D 
Its a combination of me taking a shortcut when I didn't have time, and telling myself I'd fix it later, but then the pandemic hit.

**Comment by antijingoist** [comment]
fixed.
