### ISSUE TITLE
Text not legible on website

### ISSUE THREAD

**Issue by SleeplessByte** [antijingoist/open-dyslexic#77]
![screenshot of the current main marketing website showing no contrast between background and text overlay](https://user-images.githubusercontent.com/1964376/109212570-fc408100-77af-11eb-86c6-1bdd36c13a7b.jpg)

Is this intentional?

**Comment by antijingoist** [comment]
Not intentional. Try clearing your cache refreshing. I updated bootstrap this morning and had to update the style for that reason.

**Comment by SleeplessByte** [comment]
Works again after a hard refresh!
