### ISSUE TITLE
The OpenDyslexic site is down

### ISSUE THREAD

**Issue by smoyer64** [antijingoist/open-dyslexic#80]
None of the pages I found links for work - like #71?

**Comment by antijingoist** [comment]
Thank you for the heads up. I made a mistake. 😬
Should be good now.

**Comment by smoyer64** [comment]
Awesome ... thanks so much!

**Comment by smoyer64** [comment]
After all that, I found the downloads I wanted through my GumRoad purchase confirmation email! :)
